
administration:
  connector: jira # bugzilla
  processors:
    - issues
    - documentation
    - confluence
    - rule-engine
  reporters:
    - html
    - text
  parallelExecution: false


connectors:
  jira:
    url: https://issues.apache.org/jira
    anonymous: true
    credentialsFolder: ../data/
    resolvedQuery: project = KAFKA AND resolution = Resolved ORDER BY priority DESC, updated DESC
    unresolvedQuery: project = KAFKA AND priority = Blocker AND resolution = Unresolved AND fixVersion = 2.5.0 ORDER BY priority DESC, updated DESC
    batchSize: 10
    batchDelay: 3000
    resolvedIssueFields:
      - summary
      - description
    unresolvedIssueFields:
      - "*all"

  bugzilla:
    url: https://bz.apache.org/bugzilla
    anonymous: true
    credentialsFolder: ../data/
    resolvedQuery: product = Ant, status = Close
    unresolvedQuery: product = Ant, status = Open
    batchSize: 10
    batchDelay: 3000

  confluence:
    url: https://cwiki.apache.org/confluence
    anonymous: true
    credentialsFolder: ../data/
    spaceKeys:
      - KAFKA
    limitPerRequest: 500


paragraphVectors:
  minWordFrequency: 1
  iterations: 5
  epochs: 5
  layerSize: 100
  learningRate: 0.025
  windowSize: 5
  trainWordVectors: true
  sampling: 0
  language: English


processors:
  issues:
    dataSetFile: ../data/Issues_DataSet.txt
    vectorModelFile: ../data/Issues_VectorModel.zip

  documentation:
    dataSetFile: ../data/Documentation_DataSet.txt
    vectorModelFile: ../data/Documentation_VectorModel.zip
    docsMetadataFile: ../data/Documentation_Metadata.txt
    docsListFile: ../data/Documentation_List.txt
    docsFolder: ../docs/

  confluence:
    dataSetFile: ../data/Confluence_DataSet.txt
    vectorModelFile: ../data/Confluence_VectorModel.zip
    confluenceMetadataFile: ../data/Confluence_Metadata.txt

  ruleEngine:
    rulesLocation: classpath*:*.drl


reporters:
  html:
    openBrowser: true
    htmlTemplateFileName: html-report-template.vm
    outputFile: ../output/report.html

  text:
    outputFile: ../output/report.txt
